version: "3.3"
services:

 
  training-service:
    image: imixs/imixs-ml-training-service
    environment:
      TZ: "Europe/Berlin"

      # OpenLiberty ENV
      #SEC_TLS_TRUSTDEFAULTCERTS: "true"
      
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://localhost:8080"
    ports:
      #- "9080:9080"
      - "8080:8080"


