version: "3.3"
services:

 
  training-service:
    image: imixs/imixs-ml-training-service
    environment:
      TZ: "Europe/Berlin"
      MP_OPENAPI_SERVERS: "http://localhost:8080"
    ports:
      #- "9080:9080"
      - "8080:8080"


