version: "3.3"
services:

 
  training-service:
    image: imixs/imixs-ml-training-service
    environment:
      TZ: "Europe/Berlin"
      TIKA_SERVICE_ENDPONT: "http://tika:9998/tika"

      # OpenLiberty ENV
      #SEC_TLS_TRUSTDEFAULTCERTS: "true"
      
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://localhost:8080"
    ports:
      #- "9080:9080"
      - "8080:8080"


# OCR Service
  tika: 
    image: imixs/tika
    ports:
      - "9998:9998"  




# Imixs-mL Service
  imixs-ml: 
    image: imixs/imixs-ml
    ports:
      - "8000:8000"  


