version: "3.3"
services:


# Imixs-ML-spaCy Service
  imixs-ml-spacy: 
    image: imixs/imixs-ml-spacy
    environment:
      PYTHONUNBUFFERED: 1
      TZ: "Europe/Berlin"
      MODEL_LANGUAGE: "de"

    ports:
      - "8000:8000"  


# Imixs-ML API sevice
  imixs-ml-api:
    image: imixs/imixs-ml-api
    environment:
      TZ: "Europe/Berlin"
      TIKA_SERVICE_ENDPONT: "http://tika:9998/tika"
      #TIKA_OCR_MODE: "PDF_ONLY"
      TIKA_OCR_MODE: "MIXED"
      # Payara-Micor ENV
      MP_OPENAPI_SERVERS: "http://localhost:8080"
    ports:
      #- "9080:9080"
      - "8080:8080"
      - "9009:9009"


# OCR Service
  tika: 
    image: imixs/tika
    environment:
      TZ: "Europe/Berlin"
      TIKA_CONFIG: "/tika-config.xml"
    ports:
      - "9998:9998"  
    volumes:
      - ~/git/imixs-ml/imixs-ml-training-service/src/docker/configuration/tika/tika-config.xml:/tika-config.xml



